### ISSUE TITLE
bytes encoding doesn't work with browsers

### ISSUE THREAD

**Issue by samuelcolvin** [duo-labs/py_webauthn#103]
Thanks so much for the library, just what I needed.

Also amazing to see pydantic used in libraries like this :smile:.

---

I'm having trouble using the output of `webauthn.generate_registration_options` in the browser, in particular I need `ArrayBuffer`s not strings for `challenge` and `user.id`.

The problem is that you're currently encoding strings using `urlsafe_b64encode` in `options_to_json()` which is not compatible with `atob()`.

Would you consider switching to plain `base64.b64encode`, or at least making it configurable?

With that I can using the following to convert strings to `ArrayBuffer`:

```js
const asArrayBuffer = v => Uint8Array.from(atob(v), c => c.charCodeAt(0))
```

---

Alternatively, if you have an elegant way to convert the output of `options_to_json` to make it suitable for use with `navigator.credentials.create()` in JS, it might be good to add it to the docs.

**Comment by MasterKale** [comment]
I'm going to close this issue for now assuming no news is good news. Please feel free to reopen if needed.

**Comment by samuelcolvin** [comment]
Humm, I'm not sure you're right about the spec requiring the use of `urlsafe_b64encode`

> The term Base64url Encoding refers to the base64 encoding using the URL- and filename-safe character set defined in Section 5 of [RFC4648], with all trailing '=' characters omitted (as permitted by Section 3.2) and without the inclusion of any line breaks, whitespace, or other additional characters.

This implies that you should be safe to use `base64.b64encode(...).strip(b'=')`.

Indeed from the above your use of `base64.urlsafe_b64encode(...)` is explicitly NOT compliant with the above part of the spec since `urlsafe_b64encode()` includes trailing `=`.

I think this issue should be reopened.

**Comment by MasterKale** [comment]
> Indeed from the above your use of `base64.urlsafe_b64encode(...)` is explicitly NOT compliant with the above part of the spec since `urlsafe_b64encode()` includes trailing `=`.

That fun fact is why I included a [bytes_to_base64url()](webauthn/helpers/bytes_to_base64url.py) helper (and it's corresponding `base64url_to_bytes` which encapsulates/benefits from other quirks about urlsafe_b64decode):

```py
def bytes_to_base64url(val: bytes) -> str:
    """
    Base64URL-encode the provided bytes
    """
    return urlsafe_b64encode(val).decode("utf-8").replace("=", "")
```

**Comment by samuelcolvin** [comment]
Thanks, sorry I missed that.

**Comment by samuelcolvin** [comment]
By the way, you can make this code slightly more performance and expressive with

```py
return urlsafe_b64encode(val).rstrip(b'=').decode()
```

Since `=` can only appear at the end of the string.
