### ISSUE TITLE
Type information not included in package

### ISSUE THREAD

**Issue by Majsvaffla** [duo-labs/py_webauthn#105]
Hello!

I'm using this package in a project where type annotations and type checking is used extensively. It's desirable that the sub-dependencies use type annotations as well. 

*py_webauthn* does have type annotations but *mypy* doesn't seem to pick them up. It seems that the type annotations isn't packaged properly. 

Would it be possible to [package the type information as per PEP 561](https://www.python.org/dev/peps/pep-0561/#packaging-type-information)?

**Comment by MasterKale** [comment]
Hello @Majsvaffla, thank you for reporting this. I've just published [py_webauthn@1.1.0](https://pypi.org/project/webauthn/1.1.0/) that should resolve this. Please give it a shot and let me know if it works for you 🙂

**Comment by Majsvaffla** [comment]
@MasterKale it works like a charm 👍 thanks for the speedy response 😃
