### ISSUE TITLE
Production?

### ISSUE THREAD

**Issue by drozzy** [duo-labs/py_webauthn#11]
Hi, guys.
Is it safe to use this for production?

**Comment by futureimperfect** [comment]
Hi @drozzy,

Insofar as anything WebAuthn related can be "production" ready, this module is probably ok. We haven't had any external parties review or audit the code, but have conducted internal security reviews. It's worth noting, however, that the spec is still not finalized, so this may change, and there are no guarantees of backwards compatibility. Additionally, the current PyWebAuthn implementation does not implement Token Binding ID or Authenticator Extension support, as noted in the README.

Thanks!
