### ISSUE TITLE
A typo in verify_authentication_response function documentation

### ISSUE THREAD

**Issue by alexey-nextreason** [duo-labs/py_webauthn#114]
There's a typo in documentation comments here https://github.com/duo-labs/py_webauthn/blob/387c9af04f1a11bd4a77d13881ea660ea0d02e4f/webauthn/authentication/verify_authentication_response.py#L53
should be `navigator.credentials.get()`.

**Comment by MasterKale** [comment]
@alexey-nextreason Thank you for pointing this out, I'll address this with PR #115.

**Comment by MasterKale** [comment]
It was probably overkill but I cut a new release (v1.2.1) with this typo fix. Thank you again 🦅 👁️
