### ISSUE TITLE
examples/registration.py fails

### ISSUE THREAD

**Issue by nikosft** [duo-labs/py_webauthn#118]
The script `examples/registration.py` fails with the following error

```
AttributeError: 'VerifiedRegistration' object has no attribute 'json'
```

I see that in older versions of the coder `VerifiedRegistration` was extending `WebAuthnBaseModel` which defines that method. Nevertheless, in the current version `VerifiedRegistration`  does not extend any class.

**Comment by MasterKale** [comment]
@nikosft The examples should work again if you pull down the latest `webauthn==1.3.0` :v:
