### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by hfern** [duo-labs/py_webauthn#12]
Could you clarify in `setup.py` whether this project supports python 3 currently or intends to support python 3 in the future?

**Comment by futureimperfect** [comment]
Hi @hfern,

Thanks for the suggestion! To be honest, I haven't tested PyWebAuthn with Python 3, (my bad), but I think @subyraman might have. If it's not currently supported, It's definitely something we want to support. We'll get this sorted on our end and I'll leave the issue open for now.

**Comment by Anonym-tsk** [comment]
Please do it! :)

**Comment by futureimperfect** [comment]
Hi @hfern and @Anonym-tsk,

We just added support for Python 3 in #21. Can you give it a try when you get a chance?

Thanks!

**Comment by futureimperfect** [comment]
Resolved by #21.
