### ISSUE TITLE
Empty transport type

### ISSUE THREAD

**Issue by ykursav** [duo-labs/py_webauthn#121]
1) Try to generate authentication options. (webauthn.generate_authentication_options)
2) Define credential descriptor like below:
` PublicKeyCredentialDescriptor(
                type=PublicKeyCredentialType.PUBLIC_KEY,
                id=user_creds["credential_id"],
            )
        ],`

3) Try to use public key generated on front-end with below code:
`creds = await navigator.credentials.get({publicKey: publicKey});`

4) It will throw error because transports is null.

I believe that transports should not be returned at all if not defined. Otherwise breaking the frontend. (I bypassed with deleting transport from object)
`delete publicKey.allowCredentials[0].transports;`

**Comment by MasterKale** [comment]
How have you chosen to serialize `PublicKeyCredentialRequestOptions`?

I included a `webauthn.options_to_json` helper method that you can pass output from `generate_registration_options()` or `generate_authentication_options ()` directly into that will prune unset values like `transports` from the JSON. You can see an example of its use here:

https://github.com/duo-labs/py_webauthn/blob/master/examples/authentication.py#L39

**Comment by ykursav** [comment]
Thanks. Makes sense. I passed directly to frontend that was the issue probably. ( I was doing some conversions to bytearray etc. as well)

**Comment by MasterKale** [comment]
I apologize for the inconvenience. The examples in that folder were my attempt at buying myself some time to get a proper docs site up and running to surface functionality like `options_to_json()`. It's on my TODO list, but I have no ETA 🙃

**Comment by MasterKale** [comment]
> I was doing some conversions to bytearray etc. as well

That's another reason I created `options_to_json()`! This method will also take care of encoding `bytes` to Base64URL strings so they can immediately be sent to the front end as JSON 💪
