### ISSUE TITLE
Alternative to `webauthn.helpers.options_to_json.converter`?

### ISSUE THREAD

**Issue by di** [duo-labs/py_webauthn#122]
Looks like `webauthn.helpers.options_to_json.converter` has been removed in https://github.com/duo-labs/py_webauthn/commit/81e4d789605497b117e1b3198a3323b8afa1796e. Was this a non-public API we shouldn't have been relying on? Is there a recommended replacement?

FWIW here's how we're using it: https://github.com/pypa/warehouse/blob/2c587c1fcc25c5b29a06e8cf9c93bfccb033a5f3/warehouse/utils/webauthn.py#L86-L120

**Comment by MasterKale** [comment]
The public API was always intended to be `options_to_json()` - `converter` was an implementation detail before #117 restored use of Pydantic, which offers `.json()` and `.dict()` methods that `options_to_json()` used before and resumes using now.

Are you trying to get to JSON to send to the front end? Or do you want the generated options as a plain `dict` prior to that? If it's the former I'd suggest simply passing the output from `generate_registration_options()` and `generate_authentication_options()` straight into `options_to_json()` and then passing the result straight back to the front end. See [here](https://github.com/duo-labs/py_webauthn/blob/master/examples/registration.py#L55) and [here](https://github.com/duo-labs/py_webauthn/blob/master/examples/authentication.py#L39) for examples.

Alternatively you can use `json.parse(options_to_json(options))` to get out a plain `dict` of values with unset/null values stripped out, `bytes` as Base64URL strings, and camelCased properties.

**Comment by di** [comment]
It's kind of both: we want a plain `dict` so we can use our own JSON serializer on it.

IIUC we can now call `generate_registration_options(...).dict()` and `generate_authentication_options(...).dict()` instead, correct?

> Alternatively you can use `json.parse(options_to_json(options))` to get out a plain `dict` of values with unset/null values stripped out, `bytes` as Base64URL strings, and camelCased properties.

Would that have been the original behavior of `converter`, that `.dict()` would not provide?

**Comment by MasterKale** [comment]
> IIUC we can now call generate_registration_options(...).dict() and generate_authentication_options(...).dict() instead, correct?

That's correct, `.dict()` will give you back a `dict` with all of the pythonic values, while `.json()` will give you plain JSON:

```py
# .dict()
{'rp': {'name': 'Example Co', 'id': 'example.com'}, 'user': {'id': b'ABAV6QWPBEY9WOTOA1A4', 'name': 'lee', 'display_name': 'Lee'}, 'challenge': b'1234567890', 'pub_key_cred_params': [{'type': 'public-key', 'alg': <COSEAlgorithmIdentifier.ECDSA_SHA_512: -36>}], 'timeout': 12000, 'exclude_credentials': [{'id': b'1234567890', 'type': <PublicKeyCredentialType.PUBLIC_KEY: 'public-key'>, 'transports': None}], 'authenticator_selection': {'authenticator_attachment': <AuthenticatorAttachment.PLATFORM: 'platform'>, 'resident_key': <ResidentKeyRequirement.REQUIRED: 'required'>, 'require_resident_key': True, 'user_verification': <UserVerificationRequirement.PREFERRED: 'preferred'>}, 'attestation': <AttestationConveyancePreference.DIRECT: 'direct'>}

# .json()
{"rp": {"name": "Example Co", "id": "example.com"}, "user": {"id": "QUJBVjZRV1BCRVk5V09UT0ExQTQ", "name": "lee", "display_name": "Lee"}, "challenge": "MTIzNDU2Nzg5MA", "pub_key_cred_params": [{"type": "public-key", "alg": -36}], "timeout": 12000, "exclude_credentials": [{"id": "MTIzNDU2Nzg5MA", "type": "public-key", "transports": null}], "authenticator_selection": {"authenticator_attachment": "platform", "resident_key": "required", "require_resident_key": true, "user_verification": "preferred"}, "attestation": "direct"}
```

`converter` was the cattrs-specific way of achieving everything done with the `WebAuthnBaseModel` Pydantic model - namely, it handles the following when converting to JSON:

- Converting keys from snake_case to camelCase
- Encoding `bytes` to base64url-encoded strings
- Omitting `None`s so that `nulls` do not exist in the resulting JSON

The most likely equivalent to `converter.unstructure(options)` with the latest version of the lib is calling `json.parse(options_to_json(options))`. That said I'm kinda guessing that this is equivalent - my opinionated stance on how serialization should occur is captured as `options_to_json()` and I haven't spent any time trying comparing cattrs and Pydantic behavior beyond not breaking the `options_to_json()` method API.

**Comment by di** [comment]
Thanks!

PS, for any future visitors, here's the diff:

```diff
+ import json
- from webauthn.helpers.options_to_json import converter
+ from webauthn.helpers.options_to_json import options_to_json
...
- return converter.unstructure(options)
+ return json.loads(options_to_json(options))
```
