### ISSUE TITLE
Support for Chrome caBLE v2

### ISSUE THREAD

**Issue by kwunder** [duo-labs/py_webauthn#126]
In chrome one can now use an Android phone as security key (see https://blog.millerti.me/2021/06/18/previewing-chromes-cable-v2-support-for-webauthn/ - the functionality has now made its way into the regular release of Chrome). 

This methods returns the transport method name 'cable'. For this to work properly with py_webauthn, `CABLE = 'cable'` would have to be added to the class AuthenticatorTransport in structs.py

**Comment by MasterKale** [comment]
@kwunder Support for `"cable"` is now available in `webauthn==1.5.0` on PyPI 🚀
