### ISSUE TITLE
Support for less technical developers

### ISSUE THREAD

**Issue by Charles-Rocke** [duo-labs/py_webauthn#134]
Hello, can their be assistance or a better walk through for those trying to implement this into other applications? I'm not as technical as many others here but would really like to use this for my own projects. These docs aren't as straight forward as other api docs like RapidAPI or Trinsic.id so I'm a bit lost.

**Comment by jwag956** [comment]
Agreed that one needs understanding of the spec and some glue - but that's to be expected with a toolbox/low-level library such as this. I have integrated this into Flask-Security (not released yet) so here are some things that might help get you started:
First - you need javascript on your web client - look here: https://github.com/Flask-Middleware/flask-security/tree/master/flask_security/static/js
for a simple working code - this code in fact started from the older duo-labs examples, which are no longer shipped. The inputs and output for the JS is almost exactly what pywebauthn produces/wants - so you just need a bit of glue.

This file from Flask-Security: https://github.com/Flask-Middleware/flask-security/blob/master/flask_security/webauthn.py might help you see how to call the library - though it is very specific to Flask and Flask-Security.

**Comment by bn-s** [comment]
Here's a copy and paste follow-along that you can run right here. Hopefully, it should get you started.

This should complement the walkthrough found at [webauthn.guide](https://webauthn.guide/), and the examples from this repository. It sticks very closely to them.

As you move through this, go slow and pay attention. There's a lot going on and there's absolutely no exception handling here.

## Preparation

### 1) Open up the console

This walkthrough will use github.com as the relying party. So go ahead and open up the console (dev tools -> console) in this tab.

Now copy and paste these two functions for converting between base64 strings and array buffers.

```javascript
// https://stackoverflow.com/questions/21797299/convert-base64-string-to-arraybuffer
function _base64ToArrayBuffer(base64) {
    base64 = base64
        .replace(/-/g, '+')
        .replace(/_/g, '/')
        .replace(/\s/g, '')
    const binary_string = window.atob(base64);
    const len = binary_string.length;
    const bytes = new Uint8Array(len);
    for (let i = 0; i < len; i++) {
        bytes[i] = binary_string.charCodeAt(i);
    }
    return bytes.buffer;
}

// https://stackoverflow.com/questions/9267899/arraybuffer-to-base64-encoded-string
function _arrayBufferToBase64(buffer) {
    let binary = '';
    const bytes = new Uint8Array(buffer);
    const len = bytes.byteLength;
    for (let i = 0; i < len; i++) {
        binary += String.fromCharCode(bytes[i]);
    }
    return window.btoa(binary);
}
```

### 2) Fire up a Python shell

Start a Python shell in an environment where this library (`py-webauth`) is installed. No other deps are needed.

Copy and paste the following snippet.

```python
import base64
import json
import uuid

from webauthn import (
    base64url_to_bytes,
    generate_authentication_options,
    generate_registration_options,
    options_to_json,
    verify_authentication_response,
    verify_registration_response,
)
from webauthn.helpers.cose import COSEAlgorithmIdentifier
from webauthn.helpers.structs import (
    AttestationConveyancePreference,
    AuthenticationCredential,
    PublicKeyCredentialDescriptor,
    RegistrationCredential,
    UserVerificationRequirement,
)

RP_ID = 'github.com'
RP_NAME = 'GitHub'

# This will be the 'database' where we store credentials
REGISTERED = {}
```

## Registration

Time to register our first credential.

### Step 1 [Python Shell]

Copy and paste the following. Pay attention to the `registration_options` we print at the end; you'll need it in the next step.

```python
registration_options = generate_registration_options(
    rp_id=RP_ID,
    rp_name=RP_NAME,
    user_id=str(uuid.uuid4()),
    user_name='charles.rocke@github.com',
    user_display_name='Charles-Rocke',
    attestation=AttestationConveyancePreference.NONE,
    supported_pub_key_algs=[
        COSEAlgorithmIdentifier.ECDSA_SHA_256,
        COSEAlgorithmIdentifier.RSASSA_PKCS1_v1_5_SHA_256,
    ],
    timeout=60000,
    exclude_credentials=[
        PublicKeyCredentialDescriptor(id=base64url_to_bytes(cred))
        for cred in REGISTERED.keys()
    ],
)

print(options_to_json(registration_options))
```

### Step 2 [Browser Console]

Copy and paste the following, making sure you also copy in the `registration_options` we printed in the previous step. Tjere's a comment indicating where to paste them in.

```javascript
registrationOptions = // Copy and paste the options we printed in previous step:
                      // {"rp": {"name": "GitHub", "id": "github.com"}, ...}

const publicKeyCredentialCreationOptions = {
    ...registrationOptions,
    excludeCredentials: registrationOptions.excludeCredentials.map((credential) => {
        return {
            id: _base64ToArrayBuffer(credential.id),
            type: "public-key"
        }
    }),
    challenge: _base64ToArrayBuffer(registrationOptions.challenge),
    user: {
        ...registrationOptions.user,
        id: _base64ToArrayBuffer(registrationOptions.user.id),
    },
}

const credential = await navigator.credentials.create({
    publicKey: publicKeyCredentialCreationOptions
})

const registrationData = {
    type: credential.type,
    id: credential.id,
    authenticatorAttachment: credential.authenticatorAttachment,
    rawId: _arrayBufferToBase64(credential.rawId),
    response: {
        attestationObject: _arrayBufferToBase64(credential.response.attestationObject),
        clientDataJSON: _arrayBufferToBase64(credential.response.clientDataJSON)
    }
}

console.log(registrationData)
```

### Step 3 [Python Shell]

Copy and paste the following. We also need to copy-paste in the object we `console.log()` in the browser console from the previous step (right-click on it and 'copy object') and insert it into the snippet below where indicated. This time we want to treat it as a string, so tripple quote it.

```python
_registration_data = """<paste copied registrationData object here>"""
# EG:
# _registration_data = """{
#    "type": "public-key",
#    "id": CQ1C2.....",
#    .....
# }"""

registration_verification = verify_registration_response(
    credential=RegistrationCredential.parse_raw(_registration_data),
    expected_challenge=registration_options.challenge,
    expected_origin=f'https://{registration_options.rp.id}',
    expected_rp_id=registration_options.rp.id,
    require_user_verification=True,
)

registered_cred_id = base64.b64encode(
    registration_verification.credential_id).decode()

registered_cred_pk = base64.b64encode(
    registration_verification.credential_public_key).decode()

REGISTERED[registered_cred_id] = {
    'pk': registered_cred_pk,
    'count': registration_verification.sign_count
}
```

## Authentication

If all went well we've registered a credential in our placeholder database (`REGISTERED`). Now let's authenticate with it.

### Step 1 [Python Shell]

Copy and paste the following snippet. Again, pay attention to the printed `authentication_objects` which we'll need in the next step.

```python
authentication_options = generate_authentication_options(
    rp_id=RP_ID,
    timeout=60000,
    allow_credentials=[
        PublicKeyCredentialDescriptor(id=base64url_to_bytes(cred))
        for cred in REGISTERED.keys()
    ],
    user_verification=UserVerificationRequirement.REQUIRED,
)

print(options_to_json(authentication_options))
```

### Step 2 [Browser Console]

Getting the hang of the copy-paste routine yet?

```javascript
const authenticationOptions = // Copy and paste the authentication_options we printed in previous step

const publicKeyCredentialRequestOptions = {
    challenge: _base64ToArrayBuffer(authenticationOptions.challenge),
    allowCredentials: authenticationOptions.allowCredentials.map((credential) => {
        return {
            id: _base64ToArrayBuffer(credential.id),
            type: "public-key"
        }
    }),
    timeout: 60000,
}

const assertion = await navigator.credentials.get({
    publicKey: publicKeyCredentialRequestOptions
})

const authenticationData = {
    type: assertion.type,
    id: assertion.id,
    rawId: _arrayBufferToBase64(assertion.rawId),
    response: {
        authenticatorData: _arrayBufferToBase64(assertion.response.authenticatorData),
        clientDataJSON: _arrayBufferToBase64(assertion.response.clientDataJSON),
        signature: _arrayBufferToBase64(assertion.response.signature),
        userHandle: _arrayBufferToBase64(assertion.userHandle),
    }
}

console.log(authenticationData)
```

### Step 3 [Python Shell]

Again, we'll need to copy the object we `console.log()` in the previous step and paste it in with the snippet below. Tripple quote it as before.

```python
_authentication_data = """<INSERT copied authenticationData object here>"""

authentication_data = json.loads(_authentication_data)

authentication_verification = verify_authentication_response(
    credential=AuthenticationCredential.parse_raw(_authentication_data),
    expected_challenge=authentication_options.challenge,
    expected_rp_id=authentication_options.rp_id,
    expected_origin=f'https://{authentication_options.rp_id}',
    credential_public_key=base64url_to_bytes(
        REGISTERED[authentication_data['rawId']]['pk']),
    credential_current_sign_count=REGISTERED[authentication_data['rawId']]
    ['count'],
    require_user_verification=True,
)

REGISTERED[authentication_data['rawId']][
    'count'] = authentication_verification.new_sign_count
```

## Rinse and repeat

Play around and take your time. There is nothing too technical going on here. The browser API and this library are both fairly high-level. But Webauthn is a big spec, so there are a lot of moving parts and a lot to take in.

Refer to the [W3C documentation](https://www.w3.org/TR/webauthn-2/) when you need clarification on what certain things mean.

**Comment by Charles-Rocke** [comment]
> Agreed that one needs understanding of the spec and some glue - but that's to be expected with a toolbox/low-level library such as this. I have integrated this into Flask-Security (not released yet) so here are some things that might help get you started:
> 
> First - you need javascript on your web client - look here: https://github.com/Flask-Middleware/flask-security/tree/master/flask_security/static/js
> 
> for a simple working code - this code in fact started from the older duo-labs examples, which are no longer shipped. The inputs and output for the JS is almost exactly what pywebauthn produces/wants - so you just need a bit of glue.
> 
> 
> 
> This file from Flask-Security: https://github.com/Flask-Middleware/flask-security/blob/master/flask_security/webauthn.py might help you see how to call the library - though it is very specific to Flask and Flask-Security.

I didn't realize anyone commented on this until today, thank you so much for responding!

**Comment by Charles-Rocke** [comment]
Thank you too bn-s for your response! These should be a great enough start for me to understand how to use and implement this. Thank you so much again!

**Comment by MasterKale** [comment]
I apologize for not responding sooner, I thought I had all this time but maybe I never hit submit. 

You're right that there needs to be some Getting Started kind of documentation. Along with what's been posted above, I have some other resources that might help:

- [@simplewebauthn/browser](https://www.npmjs.com/package/@simplewebauthn/browser) is a library you can use to handle the front end side of WebAuthn. SimpleWebAuthn is my personal WebAuthn project that includes both front end and back end libraries, and _coincidentally_ (😉) the output from py_webauthn can be fed into the corresponding methods in this browser library.
- There are examples of how to call the four main methods of py_webauthn in the **examples/** directory. I knew finding the time for a full suite of docs would be hard so I hoped this might be a stopgap of sorts till I can find the time.
- As far as how to structure your relying party functionality, including which values to store when, I'd recommend the [example](https://github.com/masterkale/simplewebauthn/example/) server I maintain for my personal library. It's TypeScript, so you won't be able to copy-paste anything unfortunately, but the comments in there should help communicate the general requirements of running a WebAuthn server.

**Comment by Charles-Rocke** [comment]
It's ok MasterKale and thank you I'll check that out too. I'm currently running into an error that says 
`webauthn.helpers.exceptions.InvalidRegistrationResponse: Client data challenge was not expected challenge`
It's happening after I paste in Step 2 from bn-s. When I copy and paste the registration object into the registration data and try to run the rest that error pops up. Any idea on what I should do?

**Comment by bn-s** [comment]
> I'm currently running into an error that says `webauthn.helpers.exceptions.InvalidRegistrationResponse: Client data challenge was not expected challenge` It's happening after I paste in Step 2 from bn-s. When I copy and paste the registration object into the registration data and try to run the rest that error pops up. Any idea on what I should do?

I was unable to recreate the error, so I'm only guessing here, but is there any chance you're recreating the `registration_options` at any point? A new challenge is generated each time, which might be a possible cause for the mismatch.

Out of interest, what do you get as the output of `json.loads(RegistrationCredential.parse_raw(_registration_data).response.client_data_json)['challenge']` and `base64.urlsafe_b64encode(registration_options.challenge).decode()` after pasting in the `registrationData` object from the browser console into the python shell. You should see something like this:

```python
>>> _registration_data = """{
...     "type": "public-key",
...     "id": "mVJRQJ7x2WMiB5XTIvO3UCGaNq9oolm2snM4NPRRtpJf8rsRw2HSu--Z9L3b7DAmTf3cHcHKmcB5fQ1oUb78JQ",
...     "authenticatorAttachment": "cross-platform",
...     "rawId": "mVJRQJ7x2WMiB5XTIvO3UCGaNq9oolm2snM4NPRRtpJf8rsRw2HSu++Z9L3b7DAmTf3cHcHKmcB5fQ1oUb78JQ==",
...     "response": {
...         "attestationObject": "o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YVjEOusAJGA4HG8ljoOV0wJvVx8NmnZIjc2DdjmxOu0xZWBFAAAASQAAAAAAAAAAAAAAAAAAAAAAQJlSUUCe8dljIgeV0yLzt1AhmjavaKJZtrJzODT0UbaSX/K7EcNh0rvvmfS92+wwJk393B3BypnAeX0NaFG+/CWlAQIDJiABIVggXTi/XT/RN2g/CNppNE78Jc9Xq9sKIq2ZVj6ksw8t0BYiWCDfWfmUP1iKLXLa5kzGM7vRlqvqqzy28E7xnvenAOQ8wQ==",
...         "clientDataJSON": "eyJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIiwiY2hhbGxlbmdlIjoiQkIxaTd3eExoTGloVlBsZ1d5cUFQTEQtYXZBdnRoVDJ6dko4TjRmYVR6MUJhbTZRVWZwcVJvejYzeHY4LVdhcDNmM2VqSFRibEpiMHpyNzBOUWdSU3ciLCJvcmlnaW4iOiJodHRwczovL2dpdGh1Yi5jb20iLCJjcm9zc09yaWdpbiI6ZmFsc2V9"
...     }
... }"""
>>> json.loads(RegistrationCredential.parse_raw(_registration_data).response.client_data_json)['challenge']
'BB1i7wxLhLihVPlgWyqAPLD-avAvthT2zvJ8N4faTz1Bam6QUfpqRoz63xv8-Wap3f3ejHTblJb0zr70NQgRSw'
>>> base64.urlsafe_b64encode(registration_options.challenge).decode()
'BB1i7wxLhLihVPlgWyqAPLD-avAvthT2zvJ8N4faTz1Bam6QUfpqRoz63xv8-Wap3f3ejHTblJb0zr70NQgRSw=='
```

In theory, the two strings should be identical, apart from any padding (`=`) on the end.

**Comment by bn-s** [comment]
@Charles-Rocke, I've updated my walkthrough to use [@simplewebauthn/browser](https://www.npmjs.com/package/@simplewebauthn/browser). It simplifies things greatly. Take a look and see how it works for you.

**Comment by Charles-Rocke** [comment]
I figured it out, I was using vs code instead of the shell. Each time it would run, it would create a completely new challenge.

**Comment by Charles-Rocke** [comment]
@bn-s Just seeing your response now, thank you very much! I've got it to work now. Now I'm trying to implement it using Django. I was running into the error before because each time I ran the file within the editor, it would completely re-run the file generating a new challenge.

**Comment by Charles-Rocke** [comment]
@bn-s when it comes to developing things without the browser and shell is there any chance you could help me with that?

**Comment by bn-s** [comment]
First, good to hear you got the example running.

Now, before implementing it in Django, you should take a look at the example (server and client) MasterKale has linked. The example I've provided isn't quite ready for integration into a production environment, so there are a few bits and pieces you'll need to look at. An obvious example is that you probably want to also save the transports in the database when you register credentials. You would then include them when you instantiate an instance of `PublicKeyCredentialDescriptor`.

As to whether I can help, I don't think an issue on this repository is the correct place for getting into a back and forth on specific implementations. What I would suggest is to create a public repository with your implementation. I'll check your profile in the next couple of days and open an issue in it. You can then ping me from there. I can't promise to be of much help, but if it's small, specific questions I'll do my best.

As a rough off the top of my head guide on the bare minimum you'd need to do achieve this in stock-standard Django, you'll could:

- Create a table to store credentials.
- Create a many-to-one relationship between credential and user (along with `public_key`, `credential_id`, `sign_count`, and `transports`, give the credential a `user` attribute (I believe it would look something like `user = ForeignKey(User, ...)`, but it's a while since I've used Django so I might be wrong)
- Create a credential registration view. You could easily set this up as a single route with step 1 from my example serving GET requests, and POST requests would then handle the returned registration data as in step 3. Save the challenge in the session before returning GET requests and retrieve it from the session on the POST request. Use the example from MasterKale for the client-side js.
- Create a custom login view. Assuming this is being set up as a 2FA option, the idea would be to redirect a user to an authentication challenge **before** you log the session in. Taking a quick look at Django's login view now, the quickest and safest way to do this would probably be to inherit from `django.contrib.auth.views.LoginView` and override the `form_valid()` method to return a redirect before it has a chance to call `login()` (don't take my word on this, though). Here, you would save the user id in the session so you know which user to log in if they pass the next step.
- As with the registration step, you could handle the auth challenge with a single route. GET and POST methods would correspond to Step 1 and 3 from my authentication example, respectively.
- If they pass this step, retrieve the user you stored in the session and then `login(request, user)`

Don't take any of this as exhaustive. There are probably missing pieces of the puzzle.

**Comment by Charles-Rocke** [comment]
@bn-s Thank you for your response and yes absolutely, that's actually my last question. Is there maybe a slack channel of WebAuthn enthusiasts, or something similar, that I could possibly join? I don't want to continue to blow up the issues channel.

**Comment by MasterKale** [comment]
As a matter of fact there's a [FIDO & WebAuthn Community](https://discord.gg/gZupBNDsdb) on Discord you can join to ask about WebAuthn. I and a bunch of others hang out there specifically to help others figure this stuff out, and would be happy to field any questions that might come up as you venture further down this path 🔐

**Comment by Charles-Rocke** [comment]
@MasterKale Hey thanks man! @bn-s I'll make a repo and make it public for you if you ever want to check it out, thank you guys a ton!
