### ISSUE TITLE
Doesn't work on Chrome browser on Android 

### ISSUE THREAD

**Issue by hDmtP** [duo-labs/py_webauthn#138]
It works completely fine on my pc (both Chrome and Firefox) but says `Browser not supported` when I try to register/authenticate in Android chrome.

![Screenshot_2022_0821_161657.jpg](https://user-images.githubusercontent.com/65482473/185787386-f98641a9-59eb-4911-af46-f7f188df6fc1.jpg)

**Comment by MasterKale** [comment]
Can you share the entirety of Registration Options? If you're requesting resident key with `residentKey: "required"` that's likely why, discoverable credentials aren't supported on Android right now.

**Comment by hDmtP** [comment]
**Registration** `Raw Output`

```
// Registration Options
{
  "rp": {
    "name": "Sample RP",
    "id": "localhost"
  },
  "user": {
    "id": "REDACTED by me",
    "name": "your.name@localhost",
    "displayName": "your.name@localhost"
  },
  "challenge": "REDACTED by me",
  "pubKeyCredParams": [
    {
      "type": "public-key",
      "alg": -7
    },
    {
      "type": "public-key",
      "alg": -257
    }
  ],
  "attestation": "none",
  "timeout": 60000,
  "excludeCredentials": [],
  "authenticatorSelection": {
    "requireResidentKey": false,
    "userVerification": "required"
  }
}

```
<hr>

**Authentication** `Raw Output`

```
// Authentication Options
{
  "challenge": "REDACTED by me",
  "allowCredentials": [],
  "userVerification": "required",
  "timeout": 60000,
  "rpId": "localhost"
}

```

**Comment by MasterKale** [comment]
I just realized you're testing with https://github.com/duo-labs/duo-blog-going-passwordless-with-py-webauthn! That's why it looks so familiar.

> Error: WebAuthn is not supported in this browser

This is almost definitely @simplewebauthn/browser detecting that WebAuthn is not supported. See this line in `startRegistration()` that throws an error with this exact wording:

https://github.com/MasterKale/SimpleWebAuthn/blob/master/packages/browser/src/methods/startRegistration.ts#L24

Since the code otherwise works fine, you're running into an Android issue, as opposed to anything wrong with **py_webauthn**.

**Comment by hDmtP** [comment]
I see. 

So what should I do for Android?

**Comment by MasterKale** [comment]
> So what should I do for Android?

The general answer here is to make sure your OS and apps are all up on date. I'm not sure when Android started supporting WebAuthn, though, so I don't have a good idea of a minimum version of Android to aim for.

I'm curious, what version of Android and what make and model of device are you testing with? And what version of Chrome for that matter?

**Comment by MasterKale** [comment]
I asked around, it seems Android 8 is the earliest version of Android with any WebAuthn support.

**Comment by hDmtP** [comment]
> I'm curious, what version of Android and what make and model of device are you testing with? And what version of Chrome for that matter?

Android 12
vivo 1915
Chrome version = 104.0.5112.97

**Comment by ryou90** [comment]
Hi,
I also use the combination of py_webauthn for server part and @simplewebauthn/browser for the browser implementation.
For me it runs fine in Chrome on Android, edge and firefox.

I also have _requireResidentKey_ enabled without problems.

Do you use https (ssl) ? Webauthn doesn't work on http.

[See here](https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API)

> Secure context: This feature is available only in [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) (HTTPS), in some or all [supporting browsers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API#browser_compatibility).

**Comment by MasterKale** [comment]
> Android 12
> vivo 1915
> Chrome version = 104.0.5112.97 (32-bit)

@hDmtP I'm curious, if you go to https://webauthn.io on that phone, do you see a message like this?

![Screen Shot 2022-08-31 at 4 33 30 PM](https://user-images.githubusercontent.com/5166470/187802834-237c0951-ceae-4ef6-bc01-1524db186e3a.png)

Could be the phone just doesn't support WebAuthn, for some reason. I would have no idea how to fix it, that's way outside the scope of this repo.

> Do you use https (ssl) ? Webauthn doesn't work on http, when the host is not _localhost_. Then https is required!

@ryou90 is correct, you can only use WebAuthn in a [Secure Context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts). That is, you must use either http://localhost or something served at https:// to ensure the webpage has access to WebAuthn. Can you confirm that you're accessing that site in your original screenshot over an https:// connection on your phone?

**Comment by hDmtP** [comment]
I think @ryou90 is right. I was running that on `localhost` all this time.


And yes, https://webauthn.io/ does work on my phone 

![Screenshot_2022_0901_113001.jpg](https://user-images.githubusercontent.com/65482473/187842623-44cf465c-f9a7-47ac-8d51-69664e72eb03.jpg)

**Comment by Cyrille37** [comment]
With a Samsung A41 Android 12 with Chrome 128 & Firefox 132

The register does not work, it throw "The operation either timed out or was not allowed." at https://webauthn.io/ either on https://www.passkeys.io/, https://webauthn.me/

We talk about at https://github.com/duo-labs/webauthn.io/issues/146
