### ISSUE TITLE
Support ES-256 COSEAlgorithmIdentifier

### ISSUE THREAD

**Issue by inbalzelinger** [duo-labs/py_webauthn#139]
Hey, we would appreciate if you will add `ES-256`  see https://webauthn.io/ advanced options,
New Yubikeys are require this Algorithm on registration. It then allows the user to register the Yubikey with a pin code.

once we don't have it on registration and the Yubikey isn't already registered in this browser with a pin code the registration will success but we wont be able to do authentication

**Comment by MasterKale** [comment]
Please report issues with https://webauthn.io at its repo here: https://github.com/duo-labs/webauthn.io

**Comment by inbalzelinger** [comment]
but its this library issue, I would like to ask to add to `COSEAlgorithmIdentifier` the `ES256`

**Comment by MasterKale** [comment]
Just in case I misunderstood, this library already defines ES256 (`-7`) on `COSEAlgorithmIdentifier` as its full name, `ECDSA_SHA_256`:

https://github.com/duo-labs/py_webauthn/blob/master/webauthn/helpers/cose.py#L23
