### ISSUE TITLE
Failure with latest pydantic 2.0 release

### ISSUE THREAD

**Issue by jwag956** [duo-labs/py_webauthn#156]
pydantic just released 2.0 - which seems to break webauthn:

could not import 'webauthn': cannot import name 'ModelField' from 'pydantic.fields'

**Comment by MasterKale** [comment]
Hello @jwag956, py_webauthn hasn't updated for Pydantic 2.0 so I'm not surprised. Can a project not use py_webauthn (using a version of Pydantic 1.x) with Pydantic 2.0 explicitly installed as a project dependency as well?

**Comment by jwag956** [comment]
Your dependencies just list pydantic>1.9 - so it installed 2.0 and broke. You might need to change your dependency to <2.0 until you transition.

**Comment by sevdog** [comment]
Are there any plans to update to the latest version of pydantic in a next major release?

**Comment by MasterKale** [comment]
> Your dependencies just list pydantic>1.9 - so it installed 2.0 and broke. You might need to change your dependency to <2.0 until you transition.

I want to do a quick sanity check here, it looks like I can update [this line in **setup.py**](https://github.com/duo-labs/py_webauthn/blob/master/setup.py#L54) to say this instead:

```
pydantic>=1.9.0,<2.0.0
```

...And that should buy me some time to get the library updated to support Pydantic 2.0? 🤔

**Comment by jwag956** [comment]
If you need >1.9 I would leave that in

As an aside - in general I have read and agree that putting upper limits on a package in a middleware package such as pywebauthn is discouraged since it might block entire application's from updating - on the other hand the current situation is that many applications will have to pin pedantic which they don't even depend on.

So yes - should buy time - and it will be interesting to see how quickly all the folks that use pydantic convert

**Comment by MasterKale** [comment]
@jwag956 I've published `webauthn==1.9.0` that pins Pydantic to `>=1.9.0,<2.0a0`. Can you give it a shot and see if it solves this particular issue?

**Comment by jwag956** [comment]
Yes - seems to work great - thanks again for the quick response!
