### ISSUE TITLE
Update project to support Pydantic v2.0+

### ISSUE THREAD

**Issue by MasterKale** [duo-labs/py_webauthn#159]
Pydantic 2.0 is out with breaking changes. They've helpfully provided migration docs here that I can use to get py_webauthn to track the latest evolution of this dependency:

https://docs.pydantic.dev/2.0/migration/

Based on some of the stuff I'm seeing in there this'll probably form the basis for the eventual release of "`webauthn==2.0.0`".

**Comment by ljodal** [comment]
Do you have any ideas for how to do this migration? I've had a quick look at it seems like the customisations in `WebAuthnBaseModel` is the only place where changes are required?

The two things I've picked up based on a quick look:

* Custom serialization of bytes fields: It seems like the recommended way of doing this now is to have a custom field type, using `Annotated[]` to provide a validator and serializer. That wouldn't be as magic as it currently is, but it would also be a lot more explicit.
* For the customization of initializing bytes fields using `memoryview` etc that seems to still be possible, but requires a change from using the `info` argument.

I'm happy to contribute some changes here. I'm currently looking at getting our project up on Pydantic v2, and this library is currently a blocker for that :)

**Comment by MasterKale** [comment]
Sorry for the long wait, @ljodal and @martynsmith, but I'm happy to report that `webauthn==1.10.0` is out now with support for projects using either Pydantic v1 or v2. Thank you both for your patience and contributions to adding Pydantic v2 support!
