### ISSUE TITLE
Deprecation warning with pydantic v2

### ISSUE THREAD

**Issue by sevdog** [duo-labs/py_webauthn#169]
After updating this package and pydantic (v2) there is still a deprecation warning:

> PydanticDeprecatedSince20: The `__fields_set__` attribute is deprecated, use `model_fields_set` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.1.1/migration

This private attribute seems to be accessed only here:

https://github.com/duo-labs/py_webauthn/blob/56acd35480b7fc355499e9458931dc31476ec08f/webauthn/registration/verify_registration_response.py#L201

It should be preferred to access first with the new attribute/method and then with the legacy one.

**Comment by MasterKale** [comment]
Thank you for the report, @sevdog. The library is currently attempting to support use in projects that may still be using Pydantic v1 so for now the deprecation warnings will be a thing. I'm willing to accept contributions to quiet the warnings down while maintaining v1 support if you're interested in working on that.

**Comment by MasterKale** [comment]
This should now be resolved as of the newly released `webauthn==1.11.0`
