### ISSUE TITLE
Forced dependency on pydantic for library users

### ISSUE THREAD

**Issue by jpaniagualaconich** [duo-labs/py_webauthn#171]
Users of this library need to explicitly rely on symbols that are implemented in pydantic because the public interface expects pydantic instances that have to be built using `{RegistrationCredential, AuthenticationCredential}.parse_raw` (a _v1-ism_) or `.model_validate_json`  (equivalent in v2).

In this way, `py_webauthn` dependency on `pydantic` is "contagious". It's even more complicated because the coupling is to a specific version of `pydantic`. Additionally to the `.parse_raw`/`.model_validate_json` there's also the extra need to depend on `pydantic.ValidationError`.

**Comment by MasterKale** [comment]
This enhanced behavior is now available in webauthn==1.11.0
