### ISSUE TITLE
some functions still throw pydantic.ValidationError

### ISSUE THREAD

**Issue by jpaniagualaconich** [duo-labs/py_webauthn#173]
public interface functions such as `verify_authentication_response` should not throw `pydantic.ValidationError`. There are exceptions defined in `webauthn.helpers.exceptions` that can be used to avoid depending on pydantic symbols.

**Comment by MasterKale** [comment]
Thanks for raising this @jpaniagualaconich, it would definitely be a good idea to abstract validation errors like this away. This can be undertaken as part of the effort that will fully migrate the project to Pydantic v2.

**Comment by MasterKale** [comment]
This may end up being closed out if I move forward with #195 as it would remove Pydantic as a dependency of this project.

**Comment by MasterKale** [comment]
I've merged #195 which removed Pydantic as a dependency of this project so I'm closing out any PR's and issues related to Pydantic as they're no longer needed.
