### ISSUE TITLE
Unsupported credential public key type "OKP"

### ISSUE THREAD

**Issue by di** [duo-labs/py_webauthn#175]
Hi, we use `py_webauthn` as a dependency for PyPI and recently received this report: https://github.com/pypi/warehouse/issues/14520

Looking at https://github.com/duo-labs/py_webauthn/issues/160, I see some discussion about whether the `kty` field can be a string or should be an integer, but it seems like the conclusion is that it shouldn't be a string.

However, we've had a few instances in the last ~month of users trying to use keys that result in this error, and given that the reporter suggests that their security key can be used with other identity providers, I'm wondering if this library should support it, or wether we're somehow using the library wrong.

Thanks!

**Comment by di** [comment]
Looks like this is due to https://github.com/mozilla/authenticator-rs/pull/292.

**Comment by fabien-michel** [comment]
Problem described for pypi warehouse is resolved in latest firefox nightly.
