### ISSUE TITLE
(Max) number of bytes in an auto-generated challenge is not documented

### ISSUE THREAD

**Issue by lgarron** [duo-labs/py_webauthn#188]
I can't find documentation of the number of bytes (or at least a maximum) at:

- https://duo.com/blog/going-passwordless-with-py-webauthn
- https://github.com/duo-labs/py_webauthn/blob/494373e539050b96130c28477289feec65e5e19f/webauthn/registration/generate_registration_options.py#L67

Since this is a binary value that must be stored on the server, it would be really useful to know what size to allocate in a DB column.

(I know I can work around this by specifying the challenge, but it would be useful to know how to handle the defaults.)

**Comment by MasterKale** [comment]
Thanks for raising this @lgarron, if only I had time lately to produce a proper docs site 🥲

Until then I can add a note or something to the README about this specifically.

**Comment by MasterKale** [comment]
I've merged #198 that communicates more clearly how big challenges will be when it's left up to the library to generate them (it's 64 bytes.)

I'll follow up when this is available in a new release on PyPI.

**Comment by MasterKale** [comment]
Alright, this change is out in the latest `webauthn==2.0.0` on PyPI:

https://github.com/duo-labs/py_webauthn/releases/tag/v2.0.0
