### ISSUE TITLE
what is credential_public_key?

### ISSUE THREAD

**Issue by BinhaltderBoss123** [duo-labs/py_webauthn#189]
So I want to use webauthn in python to authenticate a passkey on my website. But I don't understand wich publicCredentialKey i should use. There is a public key I can get wirh response.getPublicKey() and there is a CredentialPublicKey but thats just the JSON object with the ArrayBuffers of credential id etc. How do I get this credential public key? Or is it just a base64 encoded Version of something?

**Comment by MasterKale** [comment]
The `credential_public_key` argument that you specify when calling `verify_authentication_response()` will most reliably work with the value of `VerifiedRegistration.credential_public_key` that is returned from `verify_registration_response()`:

https://github.com/duo-labs/py_webauthn/blob/a3fb0a53869e51a29c92fd1aea0c9f3e6d34be6a/webauthn/registration/verify_registration_response.py#L279
