### ISSUE TITLE
Unsupported credential public key type "E"

### ISSUE THREAD

**Issue by otonoton** [duo-labs/py_webauthn#192]
Any idea what this could mean?

**Comment by MasterKale** [comment]
Hello @otonoton, I need more information to have any chance of helping. How are you calling which py_webauthn methods? What values are you feeding in?

**Comment by MasterKale** [comment]
There's no enough information in this issue to proceed. If you wish to reopen this issue please provide code samples, WebAuthn responses causing the issue, and anything else you can think of to help me reproduce and identity the issue.
