### ISSUE TITLE
RFC: Removing Pydantic as a dependency

### ISSUE THREAD

**Issue by MasterKale** [duo-labs/py_webauthn#196]
Trying to support the Pydantic v1/v2 migration has sucked all of the oxygen out of the room in this project for me. Pydantic was initially introduced into this project through its use in code that I wrote at Duo which eventually formed the basis of the `webauthn==1.0.0` rewrite. However since then it's led to a ton of codebase complexity in an effort to decide how best to migrate the project from Pydantic v1 to v2.

I also need to rethink some of this package's API to expose less of the internal workings. Issues like https://github.com/duo-labs/py_webauthn/issues/173 and https://github.com/duo-labs/py_webauthn/issues/191 highlight how the use of Pydantic is exposed too often, and is part of the reason why the migration from v1 to v2 has been so difficult.

Pydantic is otherwise a phenomenal library, but for the purposes of py_webauthn I think it's time to move away it.

(And come to think of it organizations that vendor all dependencies should welcome this move too as it means four less dependencies to have to update any time a new version of py_webauthn is released... 🤔)

Anyway I'm going to leave this issue open for any feedback on the idea. #195 is passing all tests so I'm inclined to move forward with this, but want to give an opportunity for anyone who might be paying attention time to chime in before I pull the trigger.

**Comment by MasterKale** [comment]
> +1 from me (obviously). When you believe #195 is ready I will happily try it out.

Thanks @jwag956, I appreciate it. If you're okay installing from a branch off GitHub then the code in #195 is ready as far as I'm concerned. I have ideas for other tweaks to follow this but I'll wait till I merge #195. The core package functionality should be preserved and work with minimal refactor needed for existing implementations.

**Comment by jwag956** [comment]
Yup - grabbing the PR is fine - I'll try to get to it this weekend.
