### ISSUE TITLE
Bug: Error on empty rp_id for CredentialCreationOptions

### ISSUE THREAD

**Issue by Chandra158** [duo-labs/py_webauthn#204]
### Overview 
While upgrading from `v1.11.1` -> `v2.0.0`, I got error in `generate_registration_options` for empty `rp_id`: 

```python
ValueError: rp_id cannot be an empty string
```  

In the latest code, this is error while earlier it was working fine.

- [Webauthn-2](https://www.w3.org/TR/webauthn-2/#dictionary-makecredentialoptions) specs suggests that `rp_id` is optional:

  _Its value’s [id](https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialrpentity-id) member specifies the [RP ID](https://www.w3.org/TR/webauthn-2/#rp-id) the credential should be [scoped](https://www.w3.org/TR/webauthn-2/#scope) to. If omitted, its value will be the [CredentialsContainer](https://w3c.github.io/webappsec-credential-management/#credentialscontainer) object’s [relevant settings object](https://html.spec.whatwg.org/multipage/webappapis.html#relevant-settings-object)'s [origin](https://html.spec.whatwg.org/multipage/webappapis.html#concept-settings-object-origin)'s [effective domain](https://html.spec.whatwg.org/multipage/origin.html#concept-origin-effective-domain). See [§ 5.4.2 Relying Party Parameters for Credential Generation (dictionary PublicKeyCredentialRpEntity)](https://www.w3.org/TR/webauthn-2/#dictionary-rp-credential-params) for further details_.

**Comment by MasterKale** [comment]
Hello @Chandra158, I intentionally made RP ID a required value to force RPs to explicitly define it. Yes, the spec allows it to be optional but I wanted to avoid incorporating some of the ambiguity of RP ID rules in the spec into this library when I rewrote the library. I don't want to change this behavior right now so I'm closing this out.
