### ISSUE TITLE
exception common base class

### ISSUE THREAD

**Issue by raylu** [duo-labs/py_webauthn#214]
right now, [all the exceptions](https://github.com/duo-labs/py_webauthn/blob/master/webauthn/helpers/exceptions.py) directly subclass `Exception`

it'd be much nicer if they shared a common `WebAuthnException` class or something so we could distinguish them from other errors

**Comment by MasterKale** [comment]
Hello @raylu (and @bschoenmaeckers) this has been addressed in `webauthn==2.2.0`

**Comment by MasterKale** [comment]
I had an issue publishing the latest version so v2.2.0 isn't available just yet. I'll follow up when it's finally available on PyPI.

**Comment by MasterKale** [comment]
Alright, I got things worked out. `webauthn==2.2.0` is now available on PyPI
