### ISSUE TITLE
JSON object must be str, not 'bytes' (SOLVED)

### ISSUE THREAD

**Issue by jrmann100** [duo-labs/py_webauthn#24]
I'm testing the Flask demo of this project, and ran into this issue upon registering and verifying keys: (from the browser console)

`Error when validating assertion on server: Assertion failed. Error: Authentication rejected. Error: the JSON object must be str, not 'bytes'.`

After some careful sleuthing, I have pinpointed the problem to `webauthn.py`, lines 556 and 874. `json.loads` is passed `decoded_cd`, which is `bytes` type and not `str`. This can be easily fixed by a conversion between the types on both lines:

`c = json.loads(decoded_cd.decode('utf-8'))`

Otherwise, this project is fantastic; I've tried almost every other Python Webauthn demo without success.

**Comment by futureimperfect** [comment]
Thanks for the kind words, @jrmann100!

Can you tell me a little more about how you're running the Flask demo? With Docker? Without? Python 2 or 3? Unfortunately, I'm unable to reproduce the issue in Python 2 or 3.

Thanks!

**Comment by jrmann100** [comment]
Okay, I set up the project again to double-check the existence of the problem.
I'm running a AWS EC2 t2.micro instance, with fully updated software (not sure how well-maintained repositories are).

Python 3's `sys.version` returns:
```
3.4.9 (default, Dec 19 2018, 23:25:54)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

I'm using a Python 3 virtual environment, packages installed from the provided requirements.txt.
`pip freeze` returns:

```
asn1crypto==0.24.0
cbor2==4.0.1
cffi==1.11.5
Click==7.0
cryptography==2.3.1
Flask==1.0.2
Flask-Login==0.4.0
Flask-SQLAlchemy==2.1
Flask-WTF==0.14.2
future==0.17.1
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10
MarkupSafe==1.1.0
pycparser==2.19
pyOpenSSL==17.5.0
six==1.11.0
SQLAlchemy==1.0.13
Werkzeug==0.14.1
WTForms==2.1
```
I am not using Docker.

**Comment by itsliang** [comment]
I encountered same issue today. I was using GCE with clean install of debian 9, python 3.5.3, python venv (virtual env), no docker.

Is it possible to change this line:
https://github.com/duo-labs/py_webauthn/blob/f080ef0e30175c7d295e69e59a8c2816e697acfa/webauthn/webauthn.py#L605

to this:
```
if (isinstance(decoded_cd, bytes)):
    decoded_cd = str(decoded_cd, 'utf-8')
c = json.loads(decoded_cd)
```
