### ISSUE TITLE
Loggin in with authenticator

### ISSUE THREAD

**Issue by Lucid-Network** [duo-labs/py_webauthn#32]
Could you show a demo about the login process with preferably an App as authenticator? Or some hints on how to set this up with the code provided? I'm lost here sadly.

**Comment by futureimperfect** [comment]
Hi @Lucid-Network,

Support for software authenticators is definitely supported, but widespread support/adoption of roaming mobile roaming authenticators that support user verification is still being worked out, and in some cases is platform specific. Google is working on some interesting stuff in this space with their CaBLE spec, which would allow for desktop browsers to seamlessly pair with a mobile phone authenticator.

In the mean time, you can get PyWebAuthn working with the [Krypton app](https://krypt.co), or perhaps with the [Soft U2F](https://github.com/github/SoftU2F) project from GitHub. Also, if you're interested in writing your own software authenticator check out [our Android WebAuthn authenticator library](https://github.com/duo-labs/android-webauthn-authenticator), which would make that process quite a bit easier, (we hope!).

Hopefully this helps! Feel free to re-open this issue if not.

Thanks!
