### ISSUE TITLE
Invalid Signature

### ISSUE THREAD

**Issue by dsanders11** [duo-labs/py_webauthn#4]
Trying to get this library working with a [Yubico Security Key](https://www.yubico.com/product/security-key-by-yubico/) (not the 2 version which supports FIDO2, that seems fairly recent). I keep running into `Invalid signature received.` when testing registration, even in the Flask demo. I'm digging into it now, but haven't had any luck so far. From what I can tell it shouldn't be a problem with usage as the security key is returning an attestation, but the library thinks the signature is wrong.

**Comment by futureimperfect** [comment]
Fixed in #9.
