### ISSUE TITLE
Cutting a new release

### ISSUE THREAD

**Issue by woodruffw** [duo-labs/py_webauthn#41]
Hello!

Would it be possible to cut a new release for the `webauthn` module in the near future? In particular, I'd like to get the changes in #38, #39, and #40 into a release for use in https://github.com/pypa/warehouse/pull/5795/ 🙂

**Comment by futureimperfect** [comment]
Hi @woodruffw,

I just cut a new release with all these changes. It's available at the link below and on PyPI.

https://github.com/duo-labs/py_webauthn/releases/tag/v0.4.5

Thanks!

**Comment by woodruffw** [comment]
Thanks!
