### ISSUE TITLE
Flask Demo: Registration is not executed 

### ISSUE THREAD

**Issue by Cyancali** [duo-labs/py_webauthn#53]
Hi,
I cloned the current version and ran the flask demo (running in venv, with python3, all requirements installed). Opening the page in the browser i tried to registrate/authenticate, but nothing happened or got displayed (also no error messages were displayed). The .db stays empty.

Terminal output for the flask demo:
```
$ python3 app.py
* Serving Flask app "app" (lazy loading)

 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on https://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 153-743-656
127.0.0.1 - - [04/Oct/2019 15:48:59] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [04/Oct/2019 15:48:59] "GET /static/js/lib/base64.js HTTP/1.1" 200 -
127.0.0.1 - - [04/Oct/2019 15:48:59] "GET /static/css/base.css HTTP/1.1" 200 -
127.0.0.1 - - [04/Oct/2019 15:48:59] "GET /static/js/webauthn.js HTTP/1.1" 200 -
127.0.0.1 - - [04/Oct/2019 15:48:59] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [04/Oct/2019 15:49:06] "POST /webauthn_begin_activate HTTP/1.1" 200 -
```
Tested with Firefox 69.0.1 (64-bit) and Chromium Version 77.0.3865.90 (Official Build) snap (64-bit)

Any suggestions to get it run (or debug) would be great!

I got a bit further by reading the web console:
Error creating credential: DOMException: "The operation is insecure."
didClickRegister https://0.0.0.0:5000/static/js/webauthn.js:64

**Comment by Cyancali** [comment]
I got a bit further by reading the web console:
Error creating credential: DOMException: "The operation is insecure."
didClickRegister https://0.0.0.0:5000/static/js/webauthn.js:64

**Comment by Cyancali** [comment]
https://github.com/duo-labs/py_webauthn/issues/45 solved my problem as well

should have read more carefully closed issues.

**Comment by futureimperfect** [comment]
Glad you figured it out, @Cyancali! Let us know if you have any other questions!
