### ISSUE TITLE
Signature counters should be optional.

### ISSUE THREAD

**Issue by jonathanverner** [duo-labs/py_webauthn#55]
The WebAuthN spec seems to allow for authenticators which do not support the signature counter (see step 17 in [7.2 Verifying an Authentication Assertion](https://www.w3.org/TR/webauthn/#verifying-asssertion)), i.e. the signature counter should only be checked if it is non-zero. However, the following code:

https://github.com/duo-labs/py_webauthn/blob/a48ab13c06ad2c44cdf226cc6b8483d45b350691/webauthn/webauthn.py#L1081

assumes it is non-zero. I think this line should be preceded by code along the lines of:

```python
           if sign_count == 0 and self.webauthn_user.sign_count == 0:
               return sign_count
```

**Comment by futureimperfect** [comment]
Once again, it looks like you’re right @jonathanverner. I want to say this was not the case in a much earlier version of the spec when this was first written, but that’s definitely how it should work now. Here’s the current language from the Editor’s Draft:

> Let `storedSignCount` be the stored signature counter value associated with `credential.id`. If `authData.signCount` is nonzero or `storedSignCount` is nonzero, then run the following sub-step

https://w3c.github.io/webauthn/#sctn-verifying-assertion

Would you like to open a PR with this change? If not I should be able to get to it soon. Thanks for reporting!

**Comment by jonathanverner** [comment]
I am sorry it took me so long for such a small change, however I was swamped with other work :-( Anyway, now I've created [a pull request](https://github.com/duo-labs/py_webauthn/pull/58)
