### ISSUE TITLE
Add a "require resident key" option

### ISSUE THREAD

**Issue by skorokithakis** [duo-labs/py_webauthn#61]
There is currently no option to require a resident key (or I don't know how to set it). Is a library change needed, or do I need something on my end?

**Comment by nickmooney** [comment]
Just want to pull in a link to PR #62 here, in which we by default set userVerification to "discouraged" -- this change just ensures that the 2FA case continues to work as expected.

In the future, we will want to look at requiring resident keys on assertion. We support various user verification requirements on credential generation, and we should likely keep some internal state about registered credentials so we can generate assertions that match those requirements. The merged PR ensures that the developer console doesn't complain, but it's not a long-term solution.

@futureimperfect any thoughts?

**Comment by MasterKale** [comment]
The [newly-released v1.0.0](https://github.com/duo-labs/py_webauthn/releases/tag/v1.0.0) includes support for requiring resident keys - search for `resident_key` in the [registration examples](https://github.com/duo-labs/py_webauthn/blob/master/examples/registration.py#L44) for more info.
