### ISSUE TITLE
Docker image fails to built

### ISSUE THREAD

**Issue by cre8** [duo-labs/py_webauthn#72]
I tried to built the docker image but it failed on step 7: 
```
Step 7/8 : RUN /app/flask_demo/create_db.py
 ---> Running in 5cee43332efa
/usr/bin/env: ‘python\r’: No such file or directory
ERROR: Service 'app' failed to build: The command '/bin/sh -c /app/flask_demo/create_db.py' returned a non-zero code: 127
```

Adding a python at the beginning solved it:
```
RUN python /app/flask_demo/create_db.py
```

Can someone confirm this? Happend with Windows 10.

**Comment by jordan-wright** [comment]
I couldn't reproduce this on my Mac, but explicitly adding the invocation of Python doesn't seem to hurt anything so I've added it.

Thanks for taking the time to send this in!
