### ISSUE TITLE
Docker installation fails: cryptography requires GCC

### ISSUE THREAD

**Issue by jrmann100** [duo-labs/py_webauthn#89]
The Dockerfile uses `python:3-slim`, which causes `docker-compose up` installation to fail since `cryptography` requires `gcc` that is not included in the slim image (source: https://github.com/docker-library/python/issues/60).

Changing:

https://github.com/duo-labs/py_webauthn/blob/4a0f8cd1db3b7635a1951a933d5a690beedf7c50/Dockerfile#L1

…to ```FROM python:3``` resolves this issue.

**Comment by MasterKale** [comment]
Thank you for calling this out, I'll go ahead and update this when the library revamp lands (see [here](https://github.com/duo-labs/py_webauthn/issues/91#issuecomment-876569117)) ✌️

**Comment by cemiboii** [comment]
> …to `FROM python:3` resolves this issue.

I recommend using an explicit version like python 3.8.0
`FROM python:3.8.0`

At least that's how it worked for me
