### ISSUE TITLE
server validation of credential failed: registration failed. error: registration rejected. error: unable to verify origin..

### ISSUE THREAD

**Issue by Sirneij** [duo-labs/py_webauthn#90]
`server validation of credential failed: registration failed. error: registration rejected. error: unable to verify origin..` 

I continuously get this error when attempting to register. I hosted the app, wriiten in Python(Flask), on heroku and the configurations are as follow:

```
RP_ID = 'nacesdecide.herokuapp.com'
RP_NAME = 'nacesdecides nacesdecide'
ORIGIN = 'https://nacesdecide.herokuapp.com/'
```
I don't know what to do to fix it currently. Besides, how do I specifically state that the registeration and assertion should use the `fingerprint sensor` of the device alone?

**Comment by MasterKale** [comment]
Try changing `ORIGIN` to `https://nacesdecide.herokuapp.com` (remove the trailing slash). I sometimes get tripped up by this, `origin` in `clientDataJSON` lacks a trailing slash:

![Screen Shot 2021-07-08 at 9 24 04 AM](https://user-images.githubusercontent.com/5166470/124957803-52c79280-dfce-11eb-8b3b-5f5f486ee64d.png)
