### ISSUE TITLE
_verify_token_binding_id does not actually verify the tokenBinding.id property

### ISSUE THREAD

**Issue by chrisdlangton** [duo-labs/py_webauthn#93]
https://github.com/duo-labs/py_webauthn/blob/master/webauthn/webauthn.py#L1285

It only checks the `tokenBinding.status` and never uses the `token_binding_id` variable or verify the `id` as the function name and documentations suggests.

Perhaps the implementer should implement the verification? If so, the function is inappropriate and should be renamed to describe the functionality it provides (and be documented to describe this too). In it's current form it misleads the implementer into believing they are using the function to actually do verification and the intent of the function implies in it's documentation this is also the function - however it does not..

So what is the proper use by implementers? What is the function actually meant to do? Is this a defect? Is it named and documented incorrectly and it is working as intended (but very differently from the name and description)?

**Comment by MasterKale** [comment]
Support for `tokenBinding` across browsers has been...["inconsistent"](https://github.com/w3c/webauthn/issues/1623)...to date. As such it is [currently being considered for deletion from L3 of the WebAuthn spec](https://github.com/w3c/webauthn/issues/1627).

Due to this I don't plan on supporting tokenBinding in the library revamp I'm preparing (see [here](https://github.com/duo-labs/py_webauthn/issues/91#issuecomment-876569117)), nor is it likely that any work will be done on the current iteration of the library to refactor this code...

**Comment by chrisdlangton** [comment]
@MasterKale I see, reading the related material and doing some research of my own I believe I understand the _perceived_ issue.

From the reports it seems that there are some implementations _on the client devices_ that are inconsistent, however many (namely Yubikey) adhere to the spec and the server is capable of authenticating the client identity / public key in a way that would avoid certain MitM and replay attacks.

Therefore a decision to remvoe sserver-side verification, without a replacement mechanism designed to meet or exceed the intent (the security characteristics) of the removed functionality, seems immature at best, negligent when we start discussing the spec. _Because_ the reason of removal is because the client devices we are attempting to authenticate are failing to meet the spec _NOT_ that teh spec is incorrect..

**Comment by chrisdlangton** [comment]
Adding a compromise, if you chose to continue with deprecation (hopefully with a sufficiently secure replacement feature) then perhaps you might follow a normal deprecation strategy?

1. log out a deprecation notice when implementations call `_verify_token_binding_id`
2. state in the deprecation notice that token binding was not verified as the implementer expected
3. offer a date / version when the  `_verify_token_binding_id` will be removed.
4. advise what functionality to use instead for the same (or better) security characteristics

Note: Logging does not functionally change this code.
Also code comments do not functionally change the code, so it is probably decent to link to the decision rationale in the code.
